import express from "express";
import PDFDocument from "pdfkit";

const router = express.Router();

router.post("/generate", async (req, res) => {
  try {
    const { repoData } = req.body;

    // PDF
    const doc = new PDFDocument({
      margin: 50,
    });

    // Headers
    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${repoData.name}-report.pdf`
    );

    doc.pipe(res);

    //
    // TITLE
    //
    doc
      .fontSize(28)
      .fillColor("#000")
      .text(
        "Repository Intelligence Report",
        {
          align: "center",
        }
      );

    doc.moveDown(2);

    //
    // REPO INFO
    //
    doc
      .fontSize(20)
      .text("Repository");

    doc.moveDown();

    doc
      .fontSize(12)
      .text(
        `Name: ${repoData.name}`
      );

    doc.text(
      `Owner: ${repoData.owner}`
    );

    doc.text(
      `Language: ${repoData.language}`
    );

    doc.text(
      `Stars: ${repoData.stars}`
    );

    doc.text(
      `Forks: ${repoData.forks}`
    );

    doc.moveDown(2);

    //
    // METRICS
    //
    doc
      .fontSize(20)
      .text("Repository Metrics");

    doc.moveDown();

    doc.text(
      `Architecture Score: ${repoData.metrics?.architectureScore}`
    );

    doc.text(
      `Maintainability Score: ${repoData.metrics?.maintainabilityScore}`
    );

    doc.text(
      `Complexity Score: ${repoData.metrics?.complexityScore}`
    );

    doc.moveDown(2);

    //
    // FRAMEWORKS
    //
    doc
      .fontSize(20)
      .text("Frameworks");

    doc.moveDown();

    repoData.frameworks?.forEach(
      (framework) => {
        doc.text(`• ${framework}`);
      }
    );

    doc.moveDown(2);

    //
    // LANGUAGES
    //
    doc
      .fontSize(20)
      .text("Languages");

    doc.moveDown();

    repoData.languages?.forEach(
      (lang) => {
        doc.text(`• ${lang}`);
      }
    );

    doc.moveDown(2);

    //
    // AI ANALYSIS
    //
    doc
      .fontSize(20)
      .text("AI Analysis");

    doc.moveDown();

    doc
      .fontSize(12)
      .text(repoData.aiAnalysis, {
        lineGap: 4,
      });

    doc.moveDown(2);

    //
    // DEPENDENCIES
    //
    doc
      .fontSize(20)
      .text("Dependencies");

    doc.moveDown();

    repoData.dependencies?.forEach(
      (dep) => {
        doc.text(`• ${dep}`);
      }
    );

    doc.moveDown(2);

    //
    // FOOTER
    //
    doc
      .fontSize(10)
      .fillColor("gray")
      .text(
        "Generated by RepoPilot AI",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message:
        "Failed to generate report",
    });
  }
});

export default router;